"""create base tables

Revision ID: c45cf3521e8d
Revises: 
Create Date: 2025-10-29 12:18:56.893006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c45cf3521e8d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tx_summary', sa.JSON(), nullable=True),
    sa.Column('client_summary', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('iban', sa.String(length=64), nullable=False),
    sa.Column('mean_sum', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('country', sa.String(length=3), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('account_status', sa.String(length=32), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('annual_turnover', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('num_transactions', sa.Integer(), nullable=False),
    sa.Column('last_tx_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_corporate', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parties_country'), 'parties', ['country'], unique=False)
    op.create_index(op.f('ix_parties_iban'), 'parties', ['iban'], unique=True)
    op.create_index(op.f('ix_parties_name'), 'parties', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parties_name'), table_name='parties')
    op.drop_index(op.f('ix_parties_iban'), table_name='parties')
    op.drop_index(op.f('ix_parties_country'), table_name='parties')
    op.drop_table('parties')
    op.drop_table('alerts')
    # ### end Alembic commands ###
