{
 "title": "New dashboard",
 "time": { "from": "2025-11-17T10:00:00.000Z", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "time_interval",
    "query": "10 minute, 30 minute, 1 hour, 1 day"
   }
  ]
 },
 "panels": [
  {
   "title": "Transactions Count last period",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select toStartOfInterval(processing_datetime, INTERVAL ${time_interval}), \ncount(distinct transaction_id)\nfrom bank_dw.transactions\ngroup by toStartOfInterval(processing_datetime, INTERVAL ${time_interval})\nhaving dateDiff('minute', toStartOfInterval(processing_datetime, INTERVAL 10 MINUTE), now() - INTERVAL 2 HOUR) > INTERVAL ${time_interval}\norder by toStartOfInterval(processing_datetime, INTERVAL ${time_interval})"
    }
   ]
  },
  {
   "title": "Amount last period",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select toStartOfInterval(processing_datetime, INTERVAL ${time_interval}), \nsum(amount)\nfrom bank_dw.transactions\ngroup by toStartOfInterval(processing_datetime, INTERVAL ${time_interval})\nhaving dateDiff('minute', toStartOfInterval(processing_datetime, INTERVAL 10 MINUTE), now() - INTERVAL 2 HOUR) > INTERVAL ${time_interval}\norder by toStartOfInterval(processing_datetime, INTERVAL ${time_interval})"
    }
   ]
  },
  {
   "title": "Creditors count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select toStartOfInterval(processing_datetime, INTERVAL ${time_interval}), \ncount(distinct creditor_name)\nfrom bank_dw.transactions\ngroup by toStartOfInterval(processing_datetime, INTERVAL ${time_interval})\nhaving dateDiff('minute', toStartOfInterval(processing_datetime, INTERVAL 10 MINUTE), now() - INTERVAL 2 HOUR) > INTERVAL ${time_interval}\n\norder by toStartOfInterval(processing_datetime, INTERVAL ${time_interval})"
    }
   ]
  },
  {
   "title": "Debitors count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select toStartOfInterval(processing_datetime, INTERVAL ${time_interval}), \ncount(distinct debtor_name)\nfrom bank_dw.transactions\ngroup by toStartOfInterval(processing_datetime, INTERVAL ${time_interval})\nhaving dateDiff('minute', toStartOfInterval(processing_datetime, INTERVAL 10 MINUTE), now() - INTERVAL 2 HOUR) > INTERVAL ${time_interval}\n\norder by toStartOfInterval(processing_datetime, INTERVAL ${time_interval})"
    }
   ]
  },
  {
   "title": "Total Amount and Count of transactions ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfInterval(processing_datetime, INTERVAL ${time_interval}) AS time,\n    count(transaction_id) AS trans_count,\n    sum(amount) AS amount\nFROM bank_dw.transactions\n-- WHERE $__timeFilter(time_interval)\nGROUP BY time\nhaving trans_count > 50\nORDER BY time"
    }
   ]
  },
  {
   "title": "Percentage of high value transactions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(t.processing_datetime, INTERVAL ${time_interval}) period,\n  count(distinct ht.transaction_id) / count(distinct t.transaction_id) * 100 high_trans_perc\nFROM bank_dw.transactions t\nleft join bank_dw.high_value_transactions ht using(transaction_id)\n\ngroup by 1\nhaving count(distinct t.transaction_id) > 50"
    }
   ]
  },
  {
   "title": "Top debitors by amount",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select debtor_name, sum(amount) amount\nfrom bank_dw.transactions\ngroup by 1\norder by amount desc\nlimit 10"
    }
   ]
  },
  {
   "title": "Top debitors by high value trans perc",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n-- toStartOfInterval(t.processing_datetime, INTERVAL ${time_interval}) period,\ndebtor_name,\n  count(distinct ht.transaction_id) / count(distinct t.transaction_id) * 100 high_trans_perc\nFROM bank_dw.transactions t\nleft join bank_dw.high_value_transactions ht using(transaction_id)\n\ngroup by 1\nhaving count(distinct t.transaction_id) > 50\norder by high_trans_perc desc\nlimit 10\n\n\n"
    }
   ]
  },
  {
   "title": "Top creditors by amount",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select creditor_name, sum(amount) amount\nfrom bank_dw.transactions\ngroup by 1\norder by amount desc\nlimit 10"
    }
   ]
  },
  {
   "title": "Top debitors by high value trans perc",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT \n-- toStartOfInterval(t.processing_datetime, INTERVAL ${time_interval}) period,\ncreditor_name,\n  count(distinct ht.transaction_id) / count(distinct t.transaction_id) * 100 high_trans_perc\nFROM bank_dw.transactions t\nleft join bank_dw.high_value_transactions ht using(transaction_id)\n\ngroup by 1\nhaving count(distinct t.transaction_id) > 50\norder by high_trans_perc desc\nlimit 10\n"
    }
   ]
  }
 ]
}